import { useEffect} from 'react';
import Head from 'next/head'
import Link from 'next/link';
import styles from '@/styles/Home.module.css'
import useCount from '@/store-proxy/data/counter/useCount';
import useUser from '@/store-sagas/data/auth/user/useUser';

export default function Home() {
  const {state, dispatch} = useCount()

  const {auth, acUserUpdate} = useUser();

  const triggerReduxSagaUpdate = () => {
    acUserUpdate({
      first_name: 'abigaile',
      last_name: 'hunter'
    })
  }
  useEffect(() => {
    console.log('auth updated = ', auth);    
  }, [auth]);

  const triggerProxyChange = () => {
    dispatch(state.count + 1);
  }
  return (
    <>
      <Head>
        <title>Homepage</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        count:{state.count}
        <button onClick={triggerProxyChange}>Trigger count increase</button>

        <button onClick={triggerReduxSagaUpdate}>Trigger saga update</button>
        <Link href="/pg2">Go to page 2</Link>


      </main>
    </>
  )
}
